name: ChatGPT
country: Taiwan
model: gpt-3.5-turbo
temperature: 0.
timeout: 300
strategy: few_shot_with_reason  # zero_shot, zero_shot_with_reason, few_shot, few_shot_with_reason
few_shot_n_example: 8  # 6 perform the best
example_path: data/raw/reason_example.jsonl
reason_output_dir: data/processed
test_data: example02.jsonl

fine_tune:
  input_dir: data/raw
  output_dir: data/processed/fine_tune
  n: 50
  strategy: no_reason
  n_epochs: 3
  train_file: example01.jsonl
  val_file: example02.jsonl
  
