version: '3.8'
services:
  # scrap_bigkinds:

  llm-reason:
    image: 0jacky/epu_denoise:model
    build:
      dockerfile: ./dockerfile/model/Dockerfile
      context: .
      args:
        UID: $USERID
        GID: $GROUPID
        USER: $DOCKER_USER
    container_name: llm-reason
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
    volumes:
      - $PWD/data:/home/$DOCKER_USER/epu_denoise/data
      - $PWD/prompt_template:/home/$DOCKER_USER/epu_denoise/prompt_template
      - $PWD/config:/home/$DOCKER_USER/epu_denoise/config
      - $PWD/log:/home/$DOCKER_USER/epu_denoise/log
      - $PWD/src/models:/home/$DOCKER_USER/epu_denoise/src/models
      - $PWD/script:/home/$DOCKER_USER/epu_denoise/script
    command: python /home/$DOCKER_USER/epu_denoise/scripts/reason.py


  compile-prompt:
    image: 0jacky/epu_denoise:model
    build:
      dockerfile: ./dockerfile/model/Dockerfile
      context: .
      args:
        UID: $USERID
        GID: $GROUPID
        USER: $DOCKER_USER
    container_name: compile-prompt
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
    volumes:
      - $PWD/prompt_template:/home/$DOCKER_USER/epu_denoise/prompt_template
      - $PWD/src/models:/home/$DOCKER_USER/epu_denoise/src/models
      - $PWD/script:/home/$DOCKER_USER/epu_denoise/script
    command: python /home/$DOCKER_USER/epu_denoise/scripts/compile_prompt.py


  llm-predict:
    image: 0jacky/epu_denoise:model
    container_name: llm_precict
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
    volumes:
      - $PWD/data:/home/$DOCKER_USER/epu_denoise/data
      - $PWD/prompt_template:/home/$DOCKER_USER/epu_denoise/prompt_template
      - $PWD/config:/home/$DOCKER_USER/epu_denoise/config
      - $PWD/log:/home/$DOCKER_USER/epu_denoise/log
      - $PWD/src/models:/home/$DOCKER_USER/epu_denoise/src/models
      - $PWD/script:/home/$DOCKER_USER/epu_denoise/script
      - $PWD/mlruns:/home/$DOCKER_USER/epu_denoise/mlruns
    command: python /home/$DOCKER_USER/epu_denoise/scripts/predict.py


  fine-tune:
    image: 0jacky/epu_denoise:model
    container_name: fine_tune
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
    volumes:
        - $PWD/data:/home/$DOCKER_USER/epu_denoise/data
        - $PWD/config:/home/$DOCKER_USER/epu_denoise/config
        - $PWD/log:/home/$DOCKER_USER/epu_denoise/log
        - $PWD/prompt_template:/home/$DOCKER_USER/epu_denoise/prompt_template
        - $PWD/src/models:/home/$DOCKER_USER/epu_denoise/src/models
        - $PWD/script:/home/$DOCKER_USER/epu_denoise/script
    command: python /home/$DOCKER_USER/epu_denoise/scripts/fine_tune.py


  # shell command: docker compose run --rm --service-ports mlflow_ui
  mlflow-ui:
    image: 0jacky/epu_denoise:model
    container_name: mlflow-ui
    ports:
      - "5050:5050"
    volumes:
      - $PWD/mlruns:/home/$DOCKER_USER/epu_denoise/mlruns
    command: mlflow ui -h 0.0.0.0 -p 5050


  # shell command: docker compose run --rm --service-ports jupyter
  jupyter-lab:
    image: 0jacky/epu_denoise:model
    container_name: jupyter-lab
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
    ports:
      - "8888:8888"
    volumes:
      - $PWD/data:/home/$DOCKER_USER/epu_denoise/data
      - $PWD/prompt_template:/home/$DOCKER_USER/epu_denoise/prompt_template
      - $PWD/src/models:/home/$DOCKER_USER/epu_denoise/src/models
      - $PWD/notebooks:/home/$DOCKER_USER/epu_denoise/notebooks
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
