version: '3.8'
services:
  llm_predict:
    image: 0jacky/epu_denoise:model
    build:
      dockerfile: ./dockerfile/model/Dockerfile
      context: .
      args:
        UID: $UID
        GID: $GID
        USER: $DOCKER_USER
    container_name: llm_precict
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
    volumes:
      - $PWD/data:/home/$DOCKER_USER/epu_denoise/data
      - $PWD/prompt_template:/home/$DOCKER_USER/epu_denoise/prompt_template
      - $PWD/config:/home/$DOCKER_USER/epu_denoise/config
      - $PWD/log:/home/$DOCKER_USER/epu_denoise/log
      - $PWD/src/models:/home/$DOCKER_USER/epu_denoise/src/models
      - $PWD/mlruns:/home/$DOCKER_USER/epu_denoise/mlruns
    command: python /home/$DOCKER_USER/epu_denoise/src/models/predict.py

  # shell command: docker compose run --rm --service-ports mlflow_ui
  mlflow_ui:
    image: 0jacky/epu_denoise:model
    container_name: mlflow_ui
    expose:
      - "5050"
    ports:
      - "5050:5050"
    volumes:
      - $PWD/mlruns:/home/$DOCKER_USER/epu_denoise/mlruns
    command: mlflow ui -h 0.0.0.0 -p 5050
