hydra:
    output_subdir: null
    run:
      dir: .

defaults:
    - model: openai
    - process: download_korean
    - _self_

prompt:
  system_message_template_path: prompt_template/system.json
  human_message_template_path: prompt_template/human.json
  fewshot_news_path: data/raw/fewshot_news
  fewshot_reasons_path: data/processed/fewshot_reasons

data:
  raw: data/raw/
  processed: data/processed/
  predict: data/predict/
