hydra:
    output_subdir: null  
    run:
      dir: .

defaults:
    - model: chatgpt
    - process: scraping
    - _self_


data:
    raw: data/raw/
    processed: data/processed/
    predict: data/predict/
