mode: csv
# mode: json

press:
  # - 경향신문
  # - 한겨레
  # - 한국일보
  - 매일경제
  # - 한국경제
begin_date: 1991-01-01
end_date: 2012-09-23
interval: 10
# begin_date: 1991-01-01
# end_date: 2023-07-29
# interval:
headless: True
timeout: 300000
